### ISSUE TITLE
NPE at net.minecraft.server.management.ServerConfigurationManager.attemptLogin(ServerConfigurationManager.java:560)

### ISSUE THREAD

**Issue by juanmuscaria** [CrucibleMC/Crucible#1]
Caso o ip de um jogador estiver banido mas o player em si não estiver isso irá causar um NPE.
```
11.12 19:11:28 [Server] INFO UUID of player UmGamer_ is 7725c5a7-7e86-3fa0-96cf-895ad384d64f
11.12 19:11:28 [Server] WARN Failed to handle packet for xxx.xxx.xxx.xxx/xxx.xxx.xxx.xxx:50406
11.12 19:11:28 [Server] INFO java.lang.NullPointerException
11.12 19:11:28 [Server] INFO at net.minecraft.server.management.ServerConfigurationManager.attemptLogin(ServerConfigurationManager.java:560) ~[oi.class:?]
11.12 19:11:28 [Server] INFO at net.minecraft.server.network.NetHandlerLoginServer.func_147326_c(NetHandlerLoginServer.java:128) ~[nn.class:?]
11.12 19:11:28 [Server] INFO at net.minecraft.server.network.NetHandlerLoginServer.func_147233_a(NetHandlerLoginServer.java:68) ~[nn.class:?]
11.12 19:11:28 [Server] INFO at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:248) ~[ej.class:?]
11.12 19:11:28 [Server] INFO at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
11.12 19:11:28 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1022) [MinecraftServer.class:?]
11.12 19:11:28 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
11.12 19:11:28 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:840) [MinecraftServer.class:?]
11.12 19:11:28 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:692) [MinecraftServer.class:?]
11.12 19:11:28 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
11.12 19:11:28 [Disconnect] User com.mojang.authlib.GameProfile@130a1714[id=7725c5a7-7e86-3fa0-96cf-895ad384d64f,name=UmGamer_,properties={},legacy=false] (xxx.xxx.xxx.xxx/xxx.xxx.xxx.xxx:50406) has disconnected, reason: Internal server error
```

**Comment by evernife** [comment]
probably fixed with 2206473064ddd436e14b884d5b6ec013ef7e0800
