### ISSUE TITLE
malisiscore Incompatibility

### ISSUE THREAD

**Issue by constantinevi6** [CrucibleMC/Crucible#100]
Like title, here is the log:

[00:25:55] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
[00:25:55] [main/INFO]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
[00:25:55] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLServerTweaker
[00:25:55] [main/INFO]: Forge Mod Loader version 7.99.4.1614 for Minecraft 1.7.10 loading
[00:25:56] [main/INFO]: Java is OpenJDK 64-Bit Server VM, version 1.8.0_302, running on Windows 10:amd64:10.0, installed at C:\Program Files\Eclipse Foundation\jdk-8.0.302.8-hotspot\jre
[00:25:56] [main/INFO]: [pw.prok.imagine.ImagineLoadingPlugin:<clinit>:26]: Loading plugin initialized!
[00:25:56] [main/WARN]: The following coremods do not have a @MCVersion annotation. They may cause problems if this is not the correct version of Minecraft for them.
[00:25:56] [main/WARN]: Missing @MCVersion: net.malisis.core.asm.MalisisCorePlugin  
[00:25:56] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[00:25:56] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[00:25:56] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[00:25:56] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[00:25:56] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[00:25:56] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[00:25:56] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[00:25:57] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[00:25:57] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[00:25:59] [main/INFO]: [ChunkCollisionTransformer] Hook registered for net.minecraft.world.World
[00:25:59] [main/INFO]: [ChunkCollisionTransformer] Hook registered for net.minecraft.world.World
[00:25:59] [main/INFO]: [ChunkCollisionTransformer] Hook registered for net.minecraft.item.ItemBlock
[00:25:59] [main/INFO]: [ChunkCollisionTransformer] Hook registered for net.minecraft.network.NetHandlerPlayServer
[00:25:59] [main/INFO]: [ChunkBlockTransformer] Hook registered for net.minecraft.world.chunk.Chunk
[00:25:59] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
[00:25:59] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
[00:25:59] [main/INFO]: Found hooks for net.minecraft.world.World (ahb)
[00:25:59] [main/INFO]: Launching wrapped minecraft {net.minecraft.server.MinecraftServer}
[00:26:00] [main/INFO]: Found hooks for net.minecraft.item.ItemBlock (abh)
[00:26:00] [main/ERROR]: Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_302]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_302]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_302]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_302]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_302]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_302]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_302]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_302]
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:46) [Crucible-1.7.10-5.2.jar:1.7.10-5.2]
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:15) [Crucible-1.7.10-5.2.jar:1.7.10-5.2]
Caused by: java.lang.VerifyError: Expecting a stackmap frame at branch target 233
Exception Details:
  Location:
    net/minecraft/item/ItemBlock.func_77648_a(Lnet/minecraft/item/ItemStack;Lnet/minecraft/entity/player/EntityPlayer;Lnet/minecraft/world/World;IIIIFFF)Z @228: ifne
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0x0000000: 2d15 0415 0515 06b6 0028 3a0b 190b b200
    0x0000010: 2da6 001a 2d15 0415 0515 06b6 0031 1007
    0x0000020: 7e04 a200 0904 3607 a700 5f19 0bb2 0034
    0x0000030: a500 5719 0bb2 0038 a500 4f19 0bb2 003c
    0x0000040: a500 4719 0b2d 1504 1505 1506 b600 409a
    0x0000050: 0038 1507 9a00 0684 05ff 1507 04a0 0006
    0x0000060: 8405 0115 0705 a000 0684 06ff 1507 06a0
    0x0000070: 0006 8406 0115 0707 a000 0684 04ff 1507
    0x0000080: 08a0 0006 8404 012b b400 469a 0005 03ac
    0x0000090: 2c15 0415 0515 0615 072b b600 4c9a 0005
    0x00000a0: 03ac 1505 1100 ffa0 0012 2ab4 0017 b600
    0x00000b0: 50b6 0056 9900 0503 ac2d 2ab4 0017 1504
    0x00000c0: 1505 1506 0315 072c 2bb6 005a 9900 a5b8
    0x00000d0: 0060 2b2c 2d2a b400 1715 0415 0515 0615
    0x00000e0: 07b6 0064 9a00 0503 ac2a 2bb6 0068 b600
    0x00000f0: 6c36 0c2a b400 172d 1504 1505 1506 1507
    0x0000100: 1708 1709 170a 150c b600 7036 0d2a 2b2c
    0x0000110: 2d15 0415 0515 0615 0717 0817 0917 0a15
    0x0000120: 0db6 0074 9900 4b2d 1504 8612 7562 8d15
    0x0000130: 0586 1275 628d 1506 8612 7562 8d2a b400
    0x0000140: 17b4 0079 b600 7d2a b400 17b4 0079 b600
    0x0000150: 810c 620d 6e2a b400 17b4 0079 b600 8412
    0x0000160: 856a b600 892b 59b4 0046 0464 b500 4604
    0x0000170: ac03 ac                                
  Stackmap Table:
    append_frame(@43,Object[#9])
    same_frame(@90)
    same_frame(@99)
    same_frame(@108)
    same_frame(@117)
    same_frame(@126)
    same_frame(@135)
    same_frame(@144)
    same_frame(@162)
    same_frame(@185)
    append_frame(@367,Integer,Integer)
    chop_frame(@369,2)

	at net.minecraft.item.Item.func_150900_l(Item.java:419) ~[adb.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:716) ~[kl.class:?]
	at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1623) ~[MinecraftServer.class:?]
	... 12 more
[00:26:00] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.lang.reflect.InvocationTargetException
[00:26:00] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:26:00] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[00:26:00] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[00:26:00] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[00:26:00] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:46)
[00:26:00] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:15)
[00:26:00] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: Caused by: cpw.mods.fml.relauncher.FMLSecurityManager$ExitTrappedException
[00:26:00] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:28)
[00:26:00] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[00:26:00] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.Runtime.exit(Runtime.java:107)
[00:26:00] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.System.exit(System.java:973)
[00:26:00] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[00:26:00] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[00:26:00] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	... 6 more

**Comment by xstmass** [comment]
![image](https://user-images.githubusercontent.com/9090102/153905990-b9922e47-c22b-495f-a426-08cf3f62f112.png)
