### ISSUE TITLE
An error：NoClassDefFoundError: joptsimple/OptionSpec

### ISSUE THREAD

**Issue by fang2006-0643** [CrucibleMC/Crucible#109]
I've put libraries in the server's working directory.
Console output：
Exception in thread "main" java.lang.NoClassDefFoundError: joptsimple/OptionSpec
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:28)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:15)
Caused by: java.lang.ClassNotFoundException: joptsimple.OptionSpec
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 4 more

What should I do.

**Comment by RehabCZ** [comment]
Your root server folder should look like sth like this
```
📁 libraries <-- libraries inside this folder
☕ server.jar <-- actual Crucible jar file
```

Note that libraries cannot be in another subfolder (except those packages)

**Comment by fang2006-0643** [comment]
I've put libraries in the server's working directory.
Error still exists
Exception in thread "main" java.lang.NoClassDefFoundError: joptsimple/OptionSpec
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:28)
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:15)
Caused by: java.lang.ClassNotFoundException: joptsimple.OptionSpec
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 4 more

**Comment by RehabCZ** [comment]
Without proper informations this exception log is useless.
Please provide additional info like:

- Java version
- File structure _(you can provide screenshot of your server root directory)_
- Launch script

Mby somebody from Crucible staff team may extend this list of requirements in order to properly determine the issue.

**Comment by fang2006-0643** [comment]
java version "1.8.0_291
![捕获](https://user-images.githubusercontent.com/73422207/173039674-f68c578f-1c3b-40d1-a364-b2e7cb9ecb5d.PNG)
"

**Comment by RehabCZ** [comment]
I'm not much a Windows guy but that looks all good to me.
Would you provide a screenshot of libraries directory ?

**Comment by fang2006-0643** [comment]
![捕获](https://user-images.githubusercontent.com/73422207/173044079-2e3f3823-c18f-4e3c-85c1-e72a61cd8a53.PNG)
The forge library version is 1614

**Comment by RyanPereiraS** [comment]
did you use the Jar provided or build from code?
If you built it yourself, try using the one available on the releases page.

**Comment by fang2006-0643** [comment]
I want to give up it......
