### ISSUE TITLE
Plugin not working (On modded and without mods)

### ISSUE THREAD

**Issue by KubiRem** [CrucibleMC/Crucible#11]
[14:20:32 ERROR]: Could not pass event SignChangeEvent to MainMC v3.5
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-1614.1.0.7]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-1614.1.0.7]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:524) [SimplePluginManager.class:1.7.10-1614.1.0.7]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:509) [SimplePluginManager.class:1.7.10-1614.1.0.7]
        at net.minecraft.network.NetHandlerPlayServer.func_147343_a(NetHandlerPlayServer.java:2348) [nh.class:?]
        at net.minecraft.network.play.client.C12PacketUpdateSign.func_148833_a(SourceFile:48) [jn.class:?]
        at net.minecraft.network.play.client.C12PacketUpdateSign.func_148833_a(SourceFile:9) [jn.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1022) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:840) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:692) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.NullPointerException
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:94) ~[ItemStack.class:1.7.10-1614.1.0.7]
        at mainmc.nothing00.functions.ItemPlugin.getItemString(ItemPlugin.java:283) ~[?:?]
        at mainmc.nothing00.functions.PluginSign.setSign(PluginSign.java:106) ~[?:?]
        at mainmc.listener.SignEvent.onChange(SignEvent.java:31) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-1614.1.0.7]

**Comment by juanmuscaria** [comment]
This is a bug with the plugin itself, it is missing a null check.
https://github.com/Nothing00Official/MainMC/blob/04538b1d569b633cc89a01c89329967e3745c485/src/mainmc/nothing00/functions/ItemPlugin.java#L283

**Comment by KubiRem** [comment]
ok thx
