### ISSUE TITLE
[QUESTION] I have problem to create a server on linux

### ISSUE THREAD

**Issue by quentin452** [CrucibleMC/Crucible#110]
I maked a server , but when i launch the server he say this 
```
You will need to add them to your server before FML and Forge will run successfully.java.lang.ClassNotFoundException: net.minecraft.launchwrapper.Launch
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:28)
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:15)
```
I want to know how to fix this

My server folder :

![Capture d’écran_2022-09-15_20-33-25](https://user-images.githubusercontent.com/42176772/190483060-9afe1d91-127c-4a63-95a2-a122c222a8b0.png)

Start.sh script : 

"/home/iamacat/Téléchargements/java/graalvm/graalvm-ce-java8-21.2.0/bin/java" -Xmx8G -Xms1G -jar Crucible-1.7.10-dev-4eab54a-server.jar nogui

**Comment by quentin452** [comment]
ok

**Comment by quentin452** [comment]
ok I put the libraries folder ,now he tells me that
```
Exception in thread "main" java.lang.NoClassDefFoundError: joptsimple/OptionSpec
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:28)
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:15)
Caused by: java.lang.ClassNotFoundException: joptsimple.OptionSpec
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 4 more
```

**Comment by quentin452** [comment]
maybe I don't have the right libraries

**Comment by xstmass** [comment]
Download libraries https://github.com/CrucibleMC/Crucible/releases

**Comment by quentin452** [comment]
thx for help
