### ISSUE TITLE
[BUG] Applecore problem (new)

### ISSUE THREAD

**Issue by ipl-adm** [CrucibleMC/Crucible#117]
Just uploaded modpack and latest Crucible - got that error:

java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159) [launchwrapper-1.13.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30) [launchwrapper-1.13.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:46) [Crucible-1.7.10-5.3.jar:1.7.10-5.4]
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:15) [Crucible-1.7.10-5.3.jar:1.7.10-5.4]
	at pro.gravit.launcher.server.launch.SimpleLaunch.run(SimpleLaunch.java:15) [ServerWrapper.jar:?]
	at pro.gravit.launcher.server.ServerWrapper.run(ServerWrapper.java:178) [ServerWrapper.jar:?]
	at pro.gravit.launcher.server.ServerWrapper.main(ServerWrapper.java:65) [ServerWrapper.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/block/BlockCake
	at net.minecraft.block.Block.func_149671_p(Block.java:314) ~[aji.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:714) ~[kl.class:?]
	at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1623) ~[MinecraftServer.class:?]
	... 15 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.block.BlockCake
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:193) ~[launchwrapper-1.13.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_312]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_312]
	at net.minecraft.block.Block.func_149671_p(Block.java:314) ~[aji.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:714) ~[kl.class:?]
	at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1623) ~[MinecraftServer.class:?]
	... 15 more
Caused by: java.lang.RuntimeException: Could not replace FoodStats.addStats call in net/minecraft/block/BlockCake.func_150036_b
   L0
    LINENUMBER 109 L0
    ALOAD 5
    ICONST_0
    INVOKEVIRTUAL net/minecraft/entity/player/EntityPlayer.func_71043_e (Z)Z
    IFEQ L1
   L2
    LINENUMBER 112 L2
    ALOAD 5
    INVOKEVIRTUAL net/minecraft/entity/player/EntityPlayer.func_71024_bL ()Lnet/minecraft/util/FoodStats;
    GETFIELD net/minecraft/util/FoodStats.field_75127_a : I
    ISTORE 6
   L3
    LINENUMBER 113 L3
    ALOAD 5
    ICONST_2
    ILOAD 6
    IADD
    INVOKESTATIC org/bukkit/craftbukkit/v1_7_R4/event/CraftEventFactory.callFoodLevelChangeEvent (Lnet/minecraft/entity/player/EntityPlayer;I)Lorg/bukkit/event/entity/FoodLevelChangeEvent;
    ASTORE 7
   L4
    LINENUMBER 115 L4
    ALOAD 7
    INVOKEVIRTUAL org/bukkit/event/entity/FoodLevelChangeEvent.isCancelled ()Z
    IFNE L5
   L6
    LINENUMBER 117 L6
    ALOAD 5
    INVOKEVIRTUAL net/minecraft/entity/player/EntityPlayer.func_71024_bL ()Lnet/minecraft/util/FoodStats;
    ALOAD 7
    INVOKEVIRTUAL org/bukkit/event/entity/FoodLevelChangeEvent.getFoodLevel ()I
    ILOAD 6
    ISUB
    LDC 0.1
    INVOKEVIRTUAL net/minecraft/util/FoodStats.func_75122_a (IF)V
   L5
    LINENUMBER 120 L5
   FRAME APPEND [I org/bukkit/event/entity/FoodLevelChangeEvent]
    ALOAD 5
    CHECKCAST net/minecraft/entity/player/EntityPlayerMP
    GETFIELD net/minecraft/entity/player/EntityPlayerMP.field_71135_a : Lnet/minecraft/network/NetHandlerPlayServer;
    NEW net/minecraft/network/play/server/S06PacketUpdateHealth
    DUP
    ALOAD 5
    CHECKCAST net/minecraft/entity/player/EntityPlayerMP
    INVOKEVIRTUAL net/minecraft/entity/player/EntityPlayerMP.getBukkitEntity ()Lorg/bukkit/craftbukkit/v1_7_R4/entity/CraftPlayer;
    INVOKEVIRTUAL org/bukkit/craftbukkit/v1_7_R4/entity/CraftPlayer.getScaledHealth ()F
    ALOAD 5
    INVOKEVIRTUAL net/minecraft/entity/player/EntityPlayer.func_71024_bL ()Lnet/minecraft/util/FoodStats;
    GETFIELD net/minecraft/util/FoodStats.field_75127_a : I
    ALOAD 5
    INVOKEVIRTUAL net/minecraft/entity/player/EntityPlayer.func_71024_bL ()Lnet/minecraft/util/FoodStats;
    GETFIELD net/minecraft/util/FoodStats.field_75125_b : F
    INVOKESPECIAL net/minecraft/network/play/server/S06PacketUpdateHealth.<init> (FIF)V
    INVOKEVIRTUAL net/minecraft/network/NetHandlerPlayServer.func_147359_a (Lnet/minecraft/network/Packet;)V
   L7
    LINENUMBER 122 L7
    ALOAD 1
    ILOAD 2
    ILOAD 3
    ILOAD 4
    INVOKEVIRTUAL net/minecraft/world/World.func_72805_g (III)I
    ICONST_1
    IADD
    ISTORE 8
   L8
    LINENUMBER 124 L8
    ILOAD 8
    BIPUSH 6
    IF_ICMPLT L9
   L10
    LINENUMBER 126 L10
    ALOAD 1
    ILOAD 2
    ILOAD 3
    ILOAD 4
    INVOKEVIRTUAL net/minecraft/world/World.func_147468_f (III)Z
    POP
    GOTO L1
   L9
    LINENUMBER 130 L9
   FRAME APPEND [I]
    ALOAD 1
    ILOAD 2
    ILOAD 3
    ILOAD 4
    ILOAD 8
    ICONST_2
    INVOKEVIRTUAL net/minecraft/world/World.func_72921_c (IIIII)Z
    POP
   L1
    LINENUMBER 133 L1
   FRAME CHOP 3
    RETURN
   L11
    LOCALVARIABLE oldFoodLevel I L3 L1 6
    LOCALVARIABLE event Lorg/bukkit/event/entity/FoodLevelChangeEvent; L4 L1 7
    LOCALVARIABLE l I L8 L1 8
    LOCALVARIABLE this Lnet/minecraft/block/BlockCake; L0 L11 0
    LOCALVARIABLE p_150036_1_ Lnet/minecraft/world/World; L0 L11 1
    LOCALVARIABLE p_150036_2_ I L0 L11 2
    LOCALVARIABLE p_150036_3_ I L0 L11 3
    LOCALVARIABLE p_150036_4_ I L0 L11 4
    LOCALVARIABLE p_150036_5_ Lnet/minecraft/entity/player/EntityPlayer; L0 L11 5
    MAXSTACK = 6
    MAXLOCALS = 9

	at squeek.applecore.asm.module.ModuleBlockFood.addOnBlockFoodEatenHook(ModuleBlockFood.java:98) ~[AppleCore-mc1.7.10-3.1.1.jar:?]
	at squeek.applecore.asm.module.ModuleBlockFood.transform(ModuleBlockFood.java:38) ~[AppleCore-mc1.7.10-3.1.1.jar:?]
	at squeek.applecore.asm.TransformerModuleHandler.transform(TransformerModuleHandler.java:41) ~[AppleCore-mc1.7.10-3.1.1.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:294) ~[launchwrapper-1.13.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:177) ~[launchwrapper-1.13.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_312]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_312]
	at net.minecraft.block.Block.func_149671_p(Block.java:314) ~[aji.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:714) ~[kl.class:?]
	at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1623) ~[MinecraftServer.class:?]
	... 15 more
[23:01:36] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.lang.reflect.InvocationTargetException
[23:01:36] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[23:01:36] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[23:01:36] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[23:01:36] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[23:01:36] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:46)
[23:01:36] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:15)
[23:01:36] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at pro.gravit.launcher.server.launch.SimpleLaunch.run(SimpleLaunch.java:15)
[23:01:36] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at pro.gravit.launcher.server.ServerWrapper.run(ServerWrapper.java:178)
[23:01:36] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at pro.gravit.launcher.server.ServerWrapper.main(ServerWrapper.java:65)
[23:01:36] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: Caused by: cpw.mods.fml.relauncher.FMLSecurityManager$ExitTrappedException
[23:01:36] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:28)
[23:01:36] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[23:01:36] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.Runtime.exit(Runtime.java:107)
[23:01:36] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.System.exit(System.java:973)
[23:01:36] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:162)
[23:01:36] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)
[23:01:36] [main/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	... 9 more

**Comment by juanmuscaria** [comment]
Duplicated of #85, use AppleCore 3.0.0
