### ISSUE TITLE
[BUG] AppleCore Crash

### ISSUE THREAD

**Issue by laserjet25** [CrucibleMC/Crucible#131]
**Describe the bug**
When trying to launch with the ResonantRise 3.4.0.3 the server almost immediately crashes.
```
1.7.10 mods folder:
Baubles-1.7.10-1.0.1.10.jar
CodeChickenLib-1.7.10-1.1.3.138-universal.jar
commons-codec-1.9.jar
commons-compress-1.8.1.jar
ForgeMultipart-1.7.10-1.2.0.345-universal.jar
ForgeRelocation-1.7.10-0.0.1.4-universal.jar
ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar
LibSandstone-1.0.0.jar
MrTJPCore-1.1.0.32-universal.jar
```

```
ae2stuff-rv3-0.5.1.9-mc1.7.10.jar
AgriCraft-1.7.10-1.5.0.jar
ancientwarfare-2.4.115-beta-MC1.7.10-FULL.jar
AOBD-2.9.1.jar
AppleCore-mc1.7.10-1.3.1.jar
appliedenergistics2-rv3-beta-6.jar
Armourers-Workshop-1.7.10-0.38.1.98.jar
Aroma1997Core-1.7.10-1.0.2.16.jar
AROMA1997S-DIMENSIONAL-WORLD-1.7.10-1.1.0.1.jar
AsieLib-1.7.10-0.4.5.jar
AuraCascade-557.jar
Automagy-1.7.10-0.28.2.jar
BACKPACK-2.0.1-1.7.X.jar
bdlib-1.9.4.109-mc1.7.10.jar
BiblioCraft[v1.11.5][MC1.7.10].jar
BIBLIOWOODS[BIOMESOPLENTY][V1.9].jar
BIBLIOWOODS[FORESTRY][V1.7].jar
BIBLIOWOODS[NATURA][V1.5].jar
BIGREACTORS-0.4.3A.jar
bigtrees-0.2-1.7.10.jar
BiomesOPlenty-1.7.10-2.1.0.1521-universal.jar
BloodMagic-1.7.10-1.3.3-17.jar
Botania r1.8-249.jar
BrandonsCore-1.0.0.12.jar
buildcraft-7.1.16.jar
buildcraft-compat-7.1.5.jar
BuildcraftAdditions-1.7.10-2.2.5.jar
Calculator-1.7.10-1.9.11.jar
Carpenters Blocks v3.3.8 - MC 1.7.10.jar
ChickenChunks-1.7.10-1.3.4.19-universal.jar
Chisel-2.9.5.11.jar
ChiselFacades-1.7.10-2.12-chiselteam.jar
ChiselTones-1.7.10-1.0-3.jar
CodeChickenCore-1.7.10-1.0.7.47-universal.jar
CoFHCore-[1.7.10]3.1.3-328.jar
CoFHLib-[1.7.10]1.1.2-184.jar
compacter-1.1.0.12-mc1.7.10.jar
compactmachines-1.7.10-1.21.jar
compactstorage-1.7.10-release-2.1.0-lts.21-universal.jar
ComputerCraft1.75.jar
Computronics-1.7.10-1.6.0.jar
COSMETICARMOR-1.7.10-1.0.5.B8-UNIVERSAL.jar
DENSEORES-1.6.2.jar
DIMENSIONAL-ANCHOR-59.0.3.jar
Draconic-Evolution-1.7.10-1.0.2h.jar
DynamicDynamos-0.2.1.jar
Emotes 1.0.1.jar
ENCHIRIDION 2-1.7.10-2.0.2A.jar
EnderCompass-1.7.10-1.2.jar
EnderCore-1.7.10-0.2.0.36_beta.jar
EnderIO-1.7.10-2.3.0.429_beta.jar
EnderIOAddons-1.7.10-2.3.0.427_beta-0.10.11.54_beta.jar
EnderStorage-1.7.10-1.4.7.37-universal.jar
EnderTech-1.7.10-0.3.2.405.jar
EnderZoo-1.7.10-1.0.15.32.jar
EnhancedPortals_1.7.10-universal-3.0.12.jar
EUREKA-1.7.10-3.0.2.jar
ExtraCells-1.7.10-2.3.14b197.jar
ExtraTiC-1.7.10-1.4.6.jar
extrautilities-1.2.12.jar
Forbidden Magic-1.7.10-0.575.jar
forestry_1.7.10-4.2.15.63.jar
Ganys End-1.11.3.jar
Ganys Nether-1.8.3.jar
Ganys Surface-1.12.8.jar
GARDENSTUFF-1.7.10-1.6.3.jar
gendustry-1.6.3.132-mc1.7.10.jar
generators-0.9.20.123-mc1.7.10.jar
GrimoireOfGaia3-1.7.10-1.2.7.jar
growthcraft-1.7.10-2.6.3-complete.jar
Guide-API-1.7.10-1.0.1-29.jar
HardcoreEnderExpansion  MC-1.7.10  v1.8.5.jar
Headcrumbs-1.7.0.jar
IGUANATINKERTWEAKS-1.7.10-2.1.5.jar
ImmersiveEngineering-0.7.7.jar
immersiveintegration-0.6.8.jar
immibis-core-59.1.4.jar
immibis-peripherals-59.0.3.jar
INPURECORE-[1.7.10]1.0.0B9-62.jar
InventoryTweaks-1.59-dev-156.jar
ironchest-1.7.10-6.0.62.742-universal.jar
IronChestMinecarts-1.0.3.jar
IvToolkit-1.2.1.jar
Jabba-1.2.2_1.7.10.jar
Java7Checker  MC-UNIVERSAL  v2.0.jar
KORESAMPLE-1.7.10-1.3.2.jar
logisticspipes-0.9.3.126.jar
LUNATRIUSCORE-1.7.10-1.1.2.21-UNIVERSAL.jar
magicalcrops-4.0.0_PUBLIC_BETA_5.jar
magicalcropsarmoury-4.0.0_PUBLIC_BETA_4.jar
magicalcropsdeco-4.0.0_PUBLIC_BETA_4a.jar
magicbees-1.7.10-2.4.0.jar
Mantle-1.7.10-0.3.2b.jar
mcjtylib-1.8.1.jar
Mekanism-1.7.10-9.1.0.281.jar
MekanismGenerators-1.7.10-9.1.0.281.jar
MekanismTools-1.7.10-9.1.0.281.jar
MineFactoryReloaded-[1.7.10]2.8.2B1-200.jar
MineTweaker3-1.7.10-3.0.10B.jar
ModTweaker2-0.9.5.jar
MoreChisels-1.7.10-1.0-28.jar
Morpheus-1.7.10-1.6.18.jar
NATURA-1.7.10-2.2.0.1.jar
neiaddons-1.12.14.40-mc1.7.10.jar
NEIIntegration-MC1.7.10-1.1.1.jar
NetherOres-[1.7.10]2.3.1-22.jar
NotEnoughItems-1.7.10-1.0.5.120-universal.jar
NotEnoughKeys-1.7.10-3.0.0b43-universal.jar
OpenBlocks-1.7.10-1.5.jar
OpenComputers-MC1.7.10-1.5.21.41-universal.jar
OPENEYE-0.6-1.7.10-SNAPSHOT-141.jar
OpenModsLib-1.7.10-0.9.jar
OpenPeripheral-1.7.10-AIO-6.jar
OreDictionaryConverter-1.6.1.jar
Pams HarvestCraft 1.7.10Lb.jar
PneumaticCraft-1.7.10-1.12.4-147-universal.jar
pressure-1.2.5.125-mc1.7.10.jar
PROJECTBLUE-1.1.4-MC1.7.10.jar
ProjectRed-1.7.10-4.7.0pre10.93-Base.jar
ProjectRed-1.7.10-4.7.0pre10.93-Compat.jar
ProjectRed-1.7.10-4.7.0pre10.93-Fabrication.jar
ProjectRed-1.7.10-4.7.0pre10.93-Integration.jar
ProjectRed-1.7.10-4.7.0pre10.93-Lighting.jar
ProjectRed-1.7.10-4.7.0pre10.93-Mechanical.jar
ProjectRed-1.7.10-4.7.0pre10.93-World.jar
QuiverBow_1.7.10_b101d.zip
QUIVERMOB_1.7.10_B14.zip
Railcraft_1.7.10-9.12.2.0.jar
RANDOMTHINGS-2.2.4.jar
RecurrentComplex-0.9.7.1.jar
RedstoneArmory-1.7.10-1.2.0-41.jar
RedstoneArsenal-[1.7.10]1.1.2-92.jar
REDSTONEPASTEMOD-1.7.10-1.6.2.jar
RefinedRelocation-mc1.7.10-1.1.16.jar
Reliquary-1.2.257.jar
ResourceLoader-1.2.jar
rftools-4.23.jar
RouterReborn-1.7.10-1.2.0.35-universal.jar
SCOTTSTWEAKS-1.7.10-1.3.1.jar
SimplyJetpacks-MC1.7.10-1.5.3.jar
SolarFlux-1.7.10-0.8b.jar
SonarCore-1.7.10-1.1.3.jar
StevesAddons-1.7.10-0.10.16.jar
STEVESCARTS2.0.0.B18.jar
STEVESFACTORYMANAGERA93.jar
STEVESWORKSHOP-0.5.1.jar
SUPERCRAFTINGFRAME-1.7.10.3.jar
TConstruct-1.7.10-1.8.8.jar
Technomancy - 0.12.5 - 1.7.10.jar
Thaumcraft Minus Thaumcraft-1.7.10-1.1.jar
THAUMCRAFT-1.7.10-4.2.3.5.jar
THAUMCRAFTNEIPLUGIN-1.7.10-1.7A.jar
thaumicenergistics-1.0.0.5.jar
ThaumicTinkerer-2.5-1.7.10-517.jar
ThermalDynamics-[1.7.10]1.2.0-171.jar
ThermalExpansion-[1.7.10]4.1.4-247.jar
ThermalFoundation-[1.7.10]1.2.6B1-116.jar
ThermalSmeltery-1.3.1.4.jar
TiCTooltips-mc1.7.10-1.2.5.jar
TMECHWORKS-1.7.10-0.2.14.100.jar
Translocator-1.7.10-1.1.2.16-universal.jar
TUBES-1.7.10-2.0.5.jar
VEINMINER-1.7.10_0.27.1.UNKNOWN.jar
WAILA-1.5.10_1.7.10.jar
WailaHarvestability-mc1.7.10-1.1.6.jar
WAILAPlugins-MC1.7.10-0.2.0-23.jar
waterhooks-1.2.1.jar
Wawla-1.0.5.120.jar
WITCHERY-1.7.10-0.24.1.jar
WR-CBE-1.7.10-1.4.1.9-UNIVERSAL.jar
ZTONES-1.7.10-2.2.1.jar
```

**To Reproduce**
1. Launch server with specified mods
2. Crash

**Expected behavior**
No crash.

**Logs**
https://pastebin.com/bY67Vjfv

**Additional context**
I have confirmed this works with forge-1.7.10-10.13.4.1614-1.7.10-universal.

**Environment (please complete the following information):**
- Crucible Version: Crucible-1.7.10-5.4
- Plugins: N/A
- Mods: Listed above
- Java Version: 1.8.0_371-b11
- OS: Win 10

**Comment by juanmuscaria** [comment]
Seems like you are using apple core, either use version 3.0.0 or [GTNH's Fork](https://github.com/GTNewHorizons/AppleCore) as other versions are incompatible with Thermos based servers.
Alongside with that, you can try adding -noverify to your JVM arguments

**Comment by laserjet25** [comment]
Sorry for the delayed reply. I tried using their fork but received a spongeforge error and the server refused to start. I'll do more testing and add details sometime tonight.

Side note: 3.0.0 from the original author works but none of the addons do (HungerOverhaul and others).

**Comment by laserjet25** [comment]
When running the latest version of GTNH AppleCore (3.2.10). (I tried a few different versions)
```
[17:12:41] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
[17:12:41] [main/INFO]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
[17:12:41] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLServerTweaker
[17:12:41] [main/INFO]: Forge Mod Loader version 7.99.4.1614 for Minecraft 1.7.10 loading
[17:12:42] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_371, running on Windows Server 2022:amd64:10.0, installed at C:\Program Files\Java\jre-1.8
[17:12:42] [main/INFO]: [pw.prok.imagine.ImagineLoadingPlugin:<clinit>:26]: Loading plugin initialized!
[17:12:42] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from AppleCore-3.2.10.jar
[17:12:42] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[17:12:42] [main/INFO]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[17:12:42] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: org.spongepowered.asm.launch.MixinTweaker
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_371]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_371]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_371]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_371]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:109) ~[launchwrapper-1.13.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_371]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_371]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_371]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_371]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:122) [launchwrapper-1.13.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30) [launchwrapper-1.13.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_371]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_371]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_371]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_371]
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:46) [Crucible-1.7.10-5.4-test.jar:1.7.10-5.4]
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:15) [Crucible-1.7.10-5.4-test.jar:1.7.10-5.4]
[17:12:42] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.reflect.InvocationTargetException
[17:12:42] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:12:42] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[17:12:42] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[17:12:42] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[17:12:42] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:46)
[17:12:42] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:15)
[17:12:42] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: cpw.mods.fml.relauncher.FMLSecurityManager$ExitTrappedException
[17:12:42] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:28)
[17:12:42] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[17:12:42] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[17:12:42] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.System.exit(Unknown Source)
[17:12:42] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:162)
[17:12:42] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)
[17:12:42] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 6 more
```

As noted above, running the original authors 3.0.0 works with HungerOverhaul and SpiceOfLife GTNH forks (they didn't for some reason originally). Based on some quick searching for the error I received with the latest 1.7.10 from the original author, I believe it is related to this: https://github.com/KettleFoundation/Kettle/issues/15

**Comment by laserjet25** [comment]
After looking into this a bit more, it seems I missed GTNH's AppleCore requirement for https://www.curseforge.com/minecraft/mc-mods/gtnhmixins

I'll do some testing tonight and probably close this out.

**Comment by laserjet25** [comment]
It seems this was caused by the lack of mixins not Crucible.
