### ISSUE TITLE
[BUG] java.io.IOException: Packet was larger than I expected

### ISSUE THREAD

**Issue by dayd21git** [CrucibleMC/Crucible#139]
**Describe the bug**
Installed a clean server. Installed mods on the server. Started the server. Connected to the server and crashed with an error.
There is no such problem when I use a **original FORGE server**: [download](https://maven.minecraftforge.net/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/forge-1.7.10-10.13.4.1614-1.7.10-installer.jar)

**Expected behavior**
I should not be kicked from the server
There is no such problem when I use a **original FORGE server**: [download](https://maven.minecraftforge.net/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/forge-1.7.10-10.13.4.1614-1.7.10-installer.jar)

<details>
    <summary>Log client:</summary>
    <pre>
[14:56:06] [Netty Client IO #1/ERROR]: NetworkDispatcher exception
io.netty.handler.codec.DecoderException: java.io.EOFException
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:263) ~[ByteToMessageDecoder.class:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:131) ~[ByteToMessageDecoder.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:173) ~[ByteToMessageDecoder.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:149) ~[ReadTimeoutHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:100) ~[AbstractNioByteChannel$NioByteUnsafe.class:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:480) ~[NioEventLoop.class:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:447) ~[NioEventLoop.class:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:341) ~[NioEventLoop.class:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) ~[SingleThreadEventExecutor$2.class:?]
	at java.lang.Thread.run(Unknown Source) ~[?:1.8.0_361]
Caused by: java.io.EOFException
	at java.util.zip.GZIPInputStream.readUByte(Unknown Source) ~[?:1.8.0_361]
	at java.util.zip.GZIPInputStream.readUShort(Unknown Source) ~[?:1.8.0_361]
	at java.util.zip.GZIPInputStream.readHeader(Unknown Source) ~[?:1.8.0_361]
	at java.util.zip.GZIPInputStream.<init>(Unknown Source) ~[?:1.8.0_361]
	at java.util.zip.GZIPInputStream.<init>(Unknown Source) ~[?:1.8.0_361]
	at net.minecraft.nbt.CompressedStreamTools.func_152457_a(CompressedStreamTools.java:60) ~[du.class:?]
	at net.minecraft.network.PacketBuffer.func_150793_b(SourceFile:89) ~[et.class:?]
	at net.minecraft.network.PacketBuffer.func_150791_c(SourceFile:116) ~[et.class:?]
	at net.minecraft.entity.DataWatcher.func_151508_b(SourceFile:278) ~[te.class:?]
	at net.minecraft.network.play.server.S1CPacketEntityMetadata.func_148837_a(SourceFile:30) ~[hw.class:?]
	at net.minecraft.util.MessageDeserializer.decode(SourceFile:40) ~[ez.class:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:232) ~[ByteToMessageDecoder.class:?]
	... 16 more
[14:56:06] [Netty Client IO #1/INFO]: Restoring client configs.
[14:56:06] [Netty Client IO #1/ERROR]: NetworkDispatcher exception
io.netty.handler.codec.DecoderException: java.io.IOException: Bad packet id 127
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:263) ~[ByteToMessageDecoder.class:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:147) ~[ByteToMessageDecoder.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:173) ~[ByteToMessageDecoder.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:149) ~[ReadTimeoutHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:100) ~[AbstractNioByteChannel$NioByteUnsafe.class:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:480) ~[NioEventLoop.class:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:447) ~[NioEventLoop.class:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:341) ~[NioEventLoop.class:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) ~[SingleThreadEventExecutor$2.class:?]
	at java.lang.Thread.run(Unknown Source) ~[?:1.8.0_361]
Caused by: java.io.IOException: Bad packet id 127
	at net.minecraft.util.MessageDeserializer.decode(SourceFile:37) ~[ez.class:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:232) ~[ByteToMessageDecoder.class:?]
	... 16 more
[14:56:06] [Netty Client IO #1/ERROR]: NetworkDispatcher exception
io.netty.handler.codec.DecoderException: java.io.IOException: Bad packet id 2431
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:263) ~[ByteToMessageDecoder.class:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:147) ~[ByteToMessageDecoder.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:173) ~[ByteToMessageDecoder.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:149) ~[ReadTimeoutHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:100) ~[AbstractNioByteChannel$NioByteUnsafe.class:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:480) ~[NioEventLoop.class:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:447) ~[NioEventLoop.class:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:341) ~[NioEventLoop.class:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) ~[SingleThreadEventExecutor$2.class:?]
	at java.lang.Thread.run(Unknown Source) ~[?:1.8.0_361]
Caused by: java.io.IOException: Bad packet id 2431
	at net.minecraft.util.MessageDeserializer.decode(SourceFile:37) ~[ez.class:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:232) ~[ByteToMessageDecoder.class:?]
	... 16 more
[14:56:06] [Netty Client IO #1/ERROR]: NetworkDispatcher exception
io.netty.handler.codec.DecoderException: java.io.IOException: Packet was larger than I expected, found 22 bytes extra whilst reading packet 0
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:263) ~[ByteToMessageDecoder.class:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:147) ~[ByteToMessageDecoder.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:173) ~[ByteToMessageDecoder.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:149) ~[ReadTimeoutHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:100) ~[AbstractNioByteChannel$NioByteUnsafe.class:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:480) ~[NioEventLoop.class:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:447) ~[NioEventLoop.class:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:341) ~[NioEventLoop.class:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) ~[SingleThreadEventExecutor$2.class:?]
	at java.lang.Thread.run(Unknown Source) ~[?:1.8.0_361]
Caused by: java.io.IOException: Packet was larger than I expected, found 22 bytes extra whilst reading packet 0
	at net.minecraft.util.MessageDeserializer.decode(SourceFile:42) ~[ez.class:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:232) ~[ByteToMessageDecoder.class:?]
	... 16 more
    </pre>
</details>
<details>
    <summary>Log server:</summary>
    <pre>
[14:55:49] [Server thread/INFO]: day-d[/127.0.0.1:53981] logged in with entity id 1319 at ([world] -187.5, 97.0, -147.5)
[14:56:06] [Server thread/INFO]: day-d has just earned the achievement [You've been installed!]
[14:56:06] [Netty IO #1/INFO]: [Thermos] Watchable object type is incorrect! Appying correct type! ( 5 -> 7)
[14:56:06] [Server thread/INFO]: day-d lost connection: Internal Exception: java.io.IOException: ϰବ࠭ࠢล젵-ꮬ＾򥰥 𠧮𢠫࠳񲠭孭ﮤ꫾÷孨半
[14:56:06] [Server thread/INFO]: day-d left the game.
    </pre>
</details>

**Environment (please complete the following information):**
- Java Version: `1.8.0_361-b09`
- OS: `Debian 11`
- Crucible Version: [[e.g. v5.3, dev-<commit hash>]](https://github.com/CrucibleMC/Crucible/releases/tag/v5.4)
- Plugins: `Plugins (1): Crucible_Server@1.7.10-5.4`
- <details>
    <summary>Mods</summary>
    <pre>
    Mods (80): Minecraft Coder Pack@9.05, Crucible Server@1.7.10-5.4,
    Forge Mod Loader@7.10.99.99, Minecraft Forge@10.13.4.1614,
    KImagine@0.2
    mods\AdvancedThaumaturgy-2.0-30.jar
    mods\Aether-1.6.jar
    mods\AetherAspects-1.2.jar
    mods\Aoatc-0.0.3-2.4.B.jar
    mods\Aobd-2.9.2.jar
    mods\AppliedenErgistics2-rv3-beta-6.jar
    mods\ArcaneEngineering-0.2.7.jar
    mods\Automagy-0.28.2.jar
    mods\Avaritia-1.13.jar
    mods\BiblioCraft[v1.11.7][MC1.7.10].jar
    mods\BiomesOPlenty-1.7.10-2.1.0.2308-universal.jar
    mods\Botania-r1.8-249.jar
    mods\Carpenter's+Blocks+v3.3.8.2+-+MC+1.7.10.jar
    mods\CodeChickenCore-1.0.7.48.jar
    mods\CraftArcanum-1.1.1.jar
    mods\DummyCore-1.13.jar
    mods\ElectroMagicTools-1.2.6.2[1.7.10].jar
    mods\EssentialCraftv4.6.1710.63.jar
    mods\EssentialThaumaturgy-1.1.11.jar
    mods\fastcraft-1.25.jar
    mods\ForbiddenMagic-0.575.jar
    mods\Forestry-4.2.16.64.jar
    mods\ForgottenRelics-1.7.3.jar
    mods\Gadomancy-1.0.7.3.jar
    mods\gilded-games-util-1.7.10-2.0.jar
    mods\ImmersiveEngineering-0.7.7.jar
    mods\industrialcraft_2_2.2.827_ex1.7.10.jar
    mods\LOTRMod-v36.15.jar
    mods\MagicalDecorations-0.3.5.jar
    mods\MagicbBees-2.4.4.jar
    mods\MagicCookies-1.0.7.1.jar
    mods\Mantle-1.7.10-0.3.2b.jar
    mods\MiddleEarthThaumaturgy-0.7.3.1a.jar
    mods\MixedMagic-1.0.jar
    mods\MrCrayfishFurnitureModv3.4.7(1.7.10).jar
    mods\NevermineTslat-1.1.2.jar
    mods\NodalMechanics-1.0.7.jar
    mods\NotEnoughEnchantIDs-1.4.3.5-1.0a.jar
    mods\NotEnoughIDs-1.4.3.5.jar
    mods\NotEnoughPotionIDs-1.2.jar
    mods\NotEnoughThaumcraftTabs-1.0.2.jar
    mods\Origin-8.0.3.jar
    mods\ParticleLib-1.jar
    mods\Pumpkifiction-1.0.jar
    mods\RedCoal-1.7.10-1.4.jar
    mods\Tainted-Magic-8.1.1.jar
    mods\TCBotaniaExoflame-1.4.jar
    mods\TcInventoryScan-1.0.11.jar
    mods\TcNodeTracker-1.1.2.jar
    mods\TConstruct-1.7.10-1.8.8.jar
    mods\ThaumaturgicalKnowledge-0.1.5.2.jar
    mods\ThaumCarpentry-0.0.1.5.jar
    mods\Thaumcraft-4.2.3.5.jar
    mods\ThaumcraftMinusThaumcraft-1.1.jar
    mods\ThaumcraftMobAspects-1.7.2-2A.jar
    mods\ThaumicAdditions-0.41-fix-by-breakbrains.jar
    mods\ThaumicBases-1.3.jar
    mods\ThaumicDyes-1.10.5-0.jar
    mods\ThaumicEnergistics-1.1.3.0.jar
    mods\ThaumicExpansion-4.1.3.jar
    mods\ThaumicExploration-1.1-53.jar
    mods\ThaumicHorizons-1.3.5.jar
    mods\ThaumicInsurgence-0.2.6.jar
    mods\ThaumicSanity-1.0.jar
    mods\ThaumicTinkerer-2.5.jar
    mods\ThaumicUpholstery-1.2.jar
    mods\ThaumPatch-1.0.2.9.jar
    mods\TWarden-1.1.1.jar
    mods\TwilightForest-2.4.3.jar
    mods\1.7.10\Baubles-1.7.10-1.0.1.10.jar
    mods\1.7.10\CodeChickenLib-1.7.10-1.1.3.141-universal.jar
    mods\1.7.10\gud_thaumicnei-1.3.0.jar
    mods\1.7.10\NotEnoughItems-1.7.10-1.0.5.120-universal.jar
    mods\ic2\EJML-core-0.26.jar
    </pre>
</details>

**Comment by Veritaris** [comment]
Hi @dayd21git 
I suggest you to use mod [PacketUnlimiter](https://github.com/gamerforEA/Minecraft-PacketUnlimiter) to unlock max S <> C packet size as workaround 
It is required on both client and server side
