### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by KubiRem** [CrucibleMC/Crucible#14]
Hello anybody that know java mayby can help me fix this issue in this plugin NoLagg

[08:46:44 ERROR]: [NoLagg Chunks] An error occured while sending chunks:
[08:46:44 WARN]: java.util.ConcurrentModificationException
[08:46:44 WARN]: at java.util.HashMap$HashIterator.nextNode(Unknown Source)
[08:46:44 WARN]: at java.util.HashMap$ValueIterator.next(Unknown Source)
[08:46:44 WARN]: at com.bergerkiller.bukkit.nolagg.chunks.ChunkSendCommand.send(ChunkSendCommand.java:33)
[08:46:44 WARN]: at com.bergerkiller.bukkit.nolagg.chunks.ChunkCompressQueue.sendNext(ChunkCompressQueue.java:171)
[08:46:44 WARN]: at com.bergerkiller.bukkit.nolagg.chunks.ChunkSendQueue.sendBatch(ChunkSendQueue.java:376)
[08:46:44 WARN]: at com.bergerkiller.bukkit.nolagg.chunks.ChunkSendQueue.update(ChunkSendQueue.java:312)
[08:46:44 WARN]: at com.bergerkiller.bukkit.nolagg.chunks.ChunkSendQueue.update(ChunkSendQueue.java:290)
[08:46:44 WARN]: at com.bergerkiller.bukkit.nolagg.chunks.ChunkSendQueue.access$100(ChunkSendQueue.java:32)
[08:46:44 WARN]: at com.bergerkiller.bukkit.nolagg.chunks.ChunkSendQueue$ChunkSendingTask.run(ChunkSendQueue.java:57)
[08:46:44 WARN]: at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:73)
[08:46:44 WARN]: at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[08:46:44 WARN]: at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:915)
[08:46:44 WARN]: at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
[08:46:44 WARN]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:852)
[08:46:44 WARN]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:702)
[08:46:44 WARN]: at java.lang.Thread.run(Unknown Source)

**Comment by KubiRem** [comment]
To anyone please. If U have some free time mayby contact me at discord KubiRemPL#6064
