### ISSUE TITLE
[BUG] Unable to start

### ISSUE THREAD

**Issue by twixi** [CrucibleMC/Crucible#144]
When start i have this error

**Logs**
[13:39:37] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
[13:39:37] [main/INFO]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
[13:39:37] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLServerTweaker
[13:39:37] [main/INFO]: Forge Mod Loader version 7.99.4.1614 for Minecraft 1.7.10 loading
[13:39:37] [main/INFO]: Java is OpenJDK 64-Bit Server VM, version 1.8.0_392, running on Linux:amd64:6.5.11-7-pve, installed at /usr/lib/jvm/java-8-openjdk-amd64/jre
[13:39:37] [main/INFO]: [pw.prok.imagine.ImagineLoadingPlugin:<clinit>:26]: Loading plugin initialized!
[13:39:37] [main/INFO]: Loading tweaker forestry.shade.javacheck.Java7Checker from 13_forestry.jar
[13:39:41] [main/WARN]: The following coremods do not have a @MCVersion annotation. They may cause problems if this is not the correct version of Minecraft for them.
[13:39:41] [main/WARN]: Missing @MCVersion: logisticspipes.asm.LogisticsPipesCoreLoader  aroma1997.core.coremod.CoreMod  cofh.asm.LoadingPlugin  mods.immibis.core.ICCoreMod  ic2.core.coremod.IC2core  
[13:39:41] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[13:39:41] [main/INFO]: Loading tweak class name forestry.shade.javacheck.Java7Checker
[13:39:41] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.FMLDeobfTweaker
[13:39:41] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[13:39:41] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLInjectionAndSortingTweaker
[13:39:41] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:39:42] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:39:42] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:39:44] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:39:44] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:39:44] [main/INFO]: Finished data injection.
[13:39:44] [main/INFO]: Finished data injection.
[13:39:44] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:39:44] [main/INFO]: Loaded library EJML-core-0.26.jar.
[13:39:44] [main/INFO]: Calling tweak class forestry.shade.javacheck.Java7Checker
[13:39:44] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.FMLDeobfTweaker
[13:39:44] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:39:44] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:39:44] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:39:44] [main/INFO]: Calling tweak class cpw.mods.fml.relauncher.CoreModManager$FMLPluginWrapper
[13:39:44] [main/INFO]: Loading tweak class name cpw.mods.fml.common.launcher.TerminalTweaker
[13:39:44] [main/INFO]: Calling tweak class cpw.mods.fml.common.launcher.TerminalTweaker
[13:39:45] [main/ERROR]: Unable to launch
java.lang.SecurityException: class "com.mojang.authlib.minecraft.MinecraftSessionService"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(ClassLoader.java:891) ~[?:1.8.0_392]
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:661) ~[?:1.8.0_392]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:754) ~[?:1.8.0_392]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_392]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473) ~[?:1.8.0_392]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[?:1.8.0_392]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[?:1.8.0_392]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[?:1.8.0_392]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_392]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[?:1.8.0_392]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_392]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[?:1.8.0_392]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_392]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:109) ~[launchwrapper-1.13.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_392]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_392]
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_392]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_392]
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048) ~[?:1.8.0_392]
	at java.lang.Class.getMethod0(Class.java:3018) ~[?:1.8.0_392]
	at java.lang.Class.getMethod(Class.java:1784) ~[?:1.8.0_392]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:156) [launchwrapper-1.13.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30) [launchwrapper-1.13.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_392]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_392]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_392]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_392]
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:46) [Crucible-1.7.10-5.4.jar:1.7.10-5.4]
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:15) [Crucible-1.7.10-5.4.jar:1.7.10-5.4]
[13:39:45] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.lang.reflect.InvocationTargetException
[13:39:45] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[13:39:45] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[13:39:45] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:39:45] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[13:39:45] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:46)
[13:39:45] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:15)
[13:39:45] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: Caused by: cpw.mods.fml.relauncher.FMLSecurityManager$ExitTrappedException
[13:39:45] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:28)
[13:39:45] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[13:39:45] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.Runtime.exit(Runtime.java:101)
[13:39:45] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.System.exit(System.java:987)
[13:39:45] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:162)
[13:39:45] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)
[13:39:45] [main/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	... 6 more

Mods: 11_extrabiomes_xl.jar
12_wild_caves.jar
13_forestry.jar
14_forestry_binnie_mods.jar
16_twilight_forest.jar
19_rotten_flesh_to_leather.jar
21_pams_harvest_craft.jar
22_mo_zombies.jar
23_nbt.jar
3_thirst_mod.jar
5_industrial_craft_advanced_solar_panel.jar
6_industrial_craft_nuclear_control.jar
8_buildcraft_additional_pipes.jar
9_buildcraft_logistics_pipes.jar
Aroma1997Core-1.7.10-1.0.2.16.jar
Aroma1997s-Dimensional-World-1.7.10-1.1.0.1.jar
buildcraft-7.1.24.jar
buildcraft-compat-7.1.8.jar
CoFHCore-[1.7.10]3.1.4-329.jar
compactmachines-1.7.10-1.21.jar
confighealth-1.7.10-2.1.jar
CraftTweaker-1.7.10-3.1.0-legacy.jar
Dimensional-Anchors-Mod-1.7.10.jar
enderlicious-1.1.2.jar
EventHelper-1.7.10-1.13.1.jar
Ganys+End-1.11.3.jar
Ganys+Nether-1.8.3.jar
GraviSuite-1.7.10-2.0.3.jar
hopperductmod-1.7.10-1.3.2.jar
HorseDupeFix-1.0.jar
Immibis-Core-1.7.10.jar
industrialcraft-2-2.2.827-experimental.jar
InfiniteInvo-1.0.52.jar
ironchest-1.7.10-6.0.62.742-universal.jar
limitedresources-1.7.10-1.1.0.jar_OFF
NetheritePlus_1.7.10_Beta0.9.jar
netherlicious-3.2.8.jar
PowerUtils-1.7.10-1.0.4.jar
Railcraft-1.7.10-9.12.2.0.jar
Slime3.1.6.jar
StorageDrawers-1.7.10-1.10.9.jar
StorageDrawers-Forestry-1.7.10-1.1.2.jar
TwoGraves-1710.1.1.jar
wolfarmor-1.3.0.1.jar

**Comment by juanmuscaria** [comment]
Something somewhere is including authlib, which it should not. Not a Crucible issue.
Check inside your mods and see what is including authlib and delete it,
