### ISSUE TITLE
[BUG] GTNH 2.4.1 can't start with  build 31a50c6.

### ISSUE THREAD

**Issue by CrazyNutLz** [CrucibleMC/Crucible#147]
我一直使用 build  81fcb90b 一切正常，今天更新build 31a50c6 无法启动。crashreport 我放到了附件，希望有所帮助。

I have been using build 81fcb90b and everything is fine, but the update build 31a50c6 cannot be started today. I have attached the crashreport, hoping it will be helpful.

[crash-2024-03-15_11.54.44-server.txt](https://github.com/CrucibleMC/Crucible/files/14610546/crash-2024-03-15_11.54.44-server.txt)

**Comment by EverNife** [comment]
This latest version allow the usage of java 21, have you tested your server with a new java version?

Also make sure to add [java9args.txt](https://github.com/CrucibleMC/Crucible/blob/staging/java9args.txt) args.

**Comment by CrazyNutLz** [comment]
我的服务端似乎没办法更新到java21使用，存在着一些列的兼容问题，这意味着新版本无法在java8下使用吗？


My server seems unable to update to use Java 21, facing a series of compatibility issues. Does this mean the new version cannot be used with Java 8?


This is the error message I got when I tried to start the server using Java 21.

`[17:16:39] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLServerTweaker
[17:16:39] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
        at java.base/java.lang.System.setSecurityManager(System.java:430) ~[?:?]
        at cpw.mods.fml.common.launcher.FMLTweaker.<init>(FMLTweaker.java:37) ~[Crucible-1.7.10-staging-31a50c6d-server.jar:1.7.10-staging-31a50c6d]
        at cpw.mods.fml.common.launcher.FMLServerTweaker.<init>(FMLServerTweaker.java:6) ~[Crucible-1.7.10-staging-31a50c6d-server.jar:1.7.10-staging-31a50c6d]
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
        at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
        at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:304) ~[?:?]
        at java.base/java.lang.Class.newInstance(Class.java:725) ~[?:?]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:122) [launchwrapper-1.13.jar:?]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:30) [launchwrapper-1.13.jar:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:46) [Crucible-1.7.10-staging-31a50c6d-server.jar:1.7.10-staging-31a50c6d]
        at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:15) [Crucible-1.7.10-staging-31a50c6d-server.jar:1.7.10-staging-31a50c6d]`

**Comment by CrazyNutLz** [comment]
I've attempted to update to Java 21 to launch the server, but it seems there are numerous compatibility issues. It appears my current version of GTNH does not support Java 21. I'll stick with the older version for now; as long as the server runs, it's fine. Thank you very much for your response.
