### ISSUE TITLE
InvocationTargetException. Server will not start.

### ISSUE THREAD

**Issue by Zilacon** [CrucibleMC/Crucible#15]
Tried switching from Thermos to this, unable to start.
Using Adopt OpenJ9 on Linux

```
[02:57:54] [main/ERROR]: Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43) [1710.jar:1.7.10-3.0]
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12) [1710.jar:1.7.10-3.0]
Caused by: java.lang.VerifyError: JVMVRFY012 stack shape inconsistent; class=net/minecraft/block/Block, method=func_149659_a(Lnet/minecraft/world/Explosion;)Z, pc=5
Exception Details:
  Location:
    net/minecraft/block/Block.func_149659_a(Lnet/minecraft/world/Explosion;)Z @5: JBifacmpne
  Reason:
    Current frame's stack size doesn't match stackmap.
  Current Frame:
    bci: @5
    flags: { }
    locals: { 'net/minecraft/block/Block', 'net/minecraft/world/Explosion' }
    stack: { integer }
  Stackmap Frame:
    bci: @10
    flags: { }
    locals: { 'net/minecraft/block/Block', 'net/minecraft/world/Explosion' }
    stack: { }
  Stackmap Table:
    same_frame(@10)
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:714) ~[kl.class:?]
	at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1632) ~[MinecraftServer.class:?]
	... 12 more
```

Entire log:
[latest.log](https://github.com/CrucibleMC/Crucible/files/4280942/latest.log)

**Comment by juanmuscaria** [comment]
Same bug as #12 and #2.
Please add `-noverify` on your JVM arguments.
I will try to make a fix for coremods that are generating invalid bytecode in the future.
As a side note: OpenJ9 is not compatible with minecraft forge and may cause some problems in the future, especially with the way that forge creates tile entities.

**Comment by Zilacon** [comment]
As long as you have this patch: https://github.com/clienthax/Thermos/commit/a15313a6e4d5e40be6b3a345c6cba8883e6d2f1b

All mods work fine. Been using OJ9 on 3 sservers no issues using that.

**Comment by Zilacon** [comment]
Yeah just tried it with -noverify, it fixes the start up error but that ENUM patch i posted above needs to be applied. It just explodes everything on start up and then crashes with ENUM errors everywhere XD.

**Comment by juanmuscaria** [comment]
https://github.com/CrucibleMC/Crucible/releases/tag/v3.1

**Comment by Zilacon** [comment]
Hey! It fully booted :D
So both problems resolved, ill be closing this now. Thanks
Gonna toss this on all 3 servers and will report any explosions if they occur.
