### ISSUE TITLE
[BUG] Run Server Crash Report

### ISSUE THREAD

**Issue by zcloudstudio** [CrucibleMC/Crucible#153]
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 5/4/24 2:56 PM
Description: Exception in server tick loop

java.lang.ExceptionInInitializerError
	at com.koloboke.collect.map.hash.HashLongObjMaps.getDefaultFactory(HashLongObjMaps.java:55)
	at com.koloboke.collect.map.hash.HashLongObjMaps.newMutableMap(HashLongObjMaps.java:95)
	at thermos.wrapper.ChunkBlockHashMap.<init>(ChunkBlockHashMap.java:12)
	at net.minecraft.world.gen.ChunkProviderServer.<init>(ChunkProviderServer.java:85)
	at net.minecraft.world.WorldServer.func_72970_h(WorldServer.java:901)
	at net.minecraft.world.World.<init>(World.java:434)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:158)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:372)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:367)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:644)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.util.NoSuchElementException
	at java.util.ServiceLoader$LazyIterator.nextService(Unknown Source)
	at java.util.ServiceLoader$LazyIterator.access$700(Unknown Source)
	at java.util.ServiceLoader$LazyIterator$2.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.ServiceLoader$LazyIterator.next(Unknown Source)
	at java.util.ServiceLoader$1.next(Unknown Source)
	at com.koloboke.collect.map.hash.HashLongObjMaps$DefaultFactoryHolder.<clinit>(HashLongObjMaps.java:39)
	... 11 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Crucible Version: 1.7.10-staging-9bdc2dd6

**Comment by EverNife** [comment]
This issue lacks information.

But It seems be inside a library that uses fastutils, can you try again on latest staging version?
Also, if the error persist, send us more info like the list of mods.

**Comment by EverNife** [comment]
Need More Info
