### ISSUE TITLE
[BUG] Crush after joining to the server

### ISSUE THREAD

**Issue by ErriourMe** [CrucibleMC/Crucible#157]
Hi! I have a server with selfwritten mod. There is no problems with Thermos, but when I upgraded to Crucible, I have a server crush after I'm joining to the server.

```
[13:36:28] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    org/bukkit/craftbukkit/v1_7_R4/entity/CraftHumanEntity.openInventory(Lorg/bukkit/inventory/InventoryView;)V @113: invokestatic
  Reason:
    Type 'java/lang/Object' (current frame, stack[1]) is not assignable to 'net/minecraft/inventory/Container'
  Current Frame:
    bci: @113
    flags: { }
    locals: { 'org/bukkit/craftbukkit/v1_7_R4/entity/CraftHumanEntity', 'org/bukkit/inventory/InventoryView', 'net/minecraft/entity/player/EntityPlayerMP', 'java/lang/Object' }
    stack: { 'net/minecraft/entity/player/EntityPlayerMP', 'java/lang/Object' }
  Bytecode:
    0x0000000: 2ab6 0038 c100 849a 0004 b12a b600 38c0
    0x0000010: 0084 b401 4cc7 0004 b12a b600 38b4 00f9
    0x0000020: 2ab6 0038 b401 aea5 0021 2ab6 0038 c000
    0x0000030: 84b4 014c bb01 b059 2ab6 0038 b400 f9b4
    0x0000040: 0168 b701 b3b6 01b7 2ab6 0038 c000 844d
    0x0000050: 2bc1 01b9 9900 0e2b c001 b9b6 01bc 4ea7
    0x0000060: 0010 bb01 4e59 2b2c b601 51b7 01bf 4e2c
    0x0000070: 2db8 015a 4e2d c700 04b1 2bb6 01c2 3a04
    0x0000080: 1904 b801 c636 052b b601 5d3a 062b b601
    0x0000090: 60b9 0163 0100 3607 2cb4 014c bb01 6559
    0x00000a0: 2db4 0168 1505 1906 1507 03b7 016b b601
    0x00000b0: 712c 2db5 01c7 2cb4 01c7 2cb6 0175 b1  
  Stackmap Table:
    same_frame(@11)
    same_frame(@25)
    same_frame(@72)
    append_frame(@98,Object[#132])
    append_frame(@111,Object[#449])
    full_frame(@122,{Object[#2],Object[#13],Object[#132],Object[#251]},{})

	at org.bukkit.craftbukkit.v1_7_R4.entity.CraftEntity.getEntity(CraftEntity.java:52) ~[CraftEntity.class:1.7.10-staging-0c25d250]
	at net.minecraft.entity.Entity.getBukkitEntity(Entity.java:1975) ~[sa.class:?]
	at net.minecraft.entity.player.EntityPlayer.getBukkitEntity(EntityPlayer.java:137) ~[yz.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.getBukkitEntity(EntityPlayerMP.java:1508) ~[mw.class:?]
	at net.minecraft.server.management.ServerConfigurationManager.attemptLogin(ServerConfigurationManager.java:538) ~[oi.class:?]
	at net.minecraft.server.network.NetHandlerLoginServer.func_147326_c(NetHandlerLoginServer.java:129) ~[nn.class:?]
	at net.minecraft.server.network.NetHandlerLoginServer.func_147233_a(NetHandlerLoginServer.java:69) ~[nn.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:275) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) ~[nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1026) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:462) ~[lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:845) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:695) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_402]

```

**Additional context**
By the code, `openInventory` is using in the CustomNPCs mod. I tryed to turn off all plugins already, the same crush.

**Environment (please complete the following information):**
- Crucible Version: `1.7.10-staging-0c25d250`
- Plugins (20): `AutoSaveWorld@4.15, PrometheusExporter@2.1.1, WorldEdit@6.0;3342-78f975b9, MaxBans@2.3, OpenInv@2.2.7, Essentials@Pre2.14.1.3, VoxelSniper@5.170.0-SNAPSHOT-jnks317-gitfcb8fe1, iConomy@7.0, PermissionsEx@1.22.6, PlugMan@2.0.2, WorldEditFIX@12.0, Vault@1.5.6-b49, HideStream@3.3, TimingsPatch@0.1, ChatManager@1.19.1, EssentialsSpawn@Pre2.14.1.3, Multiverse-Core@2.5-b691, WorldGuard@5.6.6-SNAPSHOT, Multiverse-Portals@2.5-b699, Crucible_Server@1.7.10-staging-0c25d250`
- Mods (52): `Minecraft Coder Pack@9.05, Crucible Server@1.7.10-staging-0c25d250, Forge Mod Loader@7.10.99.99, Minecraft Forge@10.13.4.1614, KImagine@0.2, CodeChicken Core@1.0.7.47, packetapi@1.3.1, Carpenter's Blocks@3.3.8.1, Chisel@1.5.8.6, Custom Stuff 3@0.7.10, DrZhark's Mo'Creatures Mod@6.3.1, EventHelper@1.7.10-1.11, examplemod@1.0, Extra Doors@1.5.1, Fall@1.0.0, HolyLight Decor Mod@0.0.3, IronFence@1.1.0, Uncle Jeff's Walls Mod@v1.7.10-00.01.05 Beta, KeyAndCodeLock@1.4, mcf_lootpacks@0.13, Core@0.13, mcf_tempbuffs@0.13, mcf_drugs@0.13, mcf_slotmachines@0.13, Clan Mod@1.0.0, MCF S.P.E.C.I.A.L.@0.13, MCF Perks@0.13, Friend Mod@1.0.0, Flags Mode@2.0, MBot Core Mod@1.0.0, syncsafechests@0.13, mcf_phantom_blocks@0.13, mcf_disassemble@0.13, Trade Mod@1.0.0, mcf_clanitems@0.13, mcf_core@0.13, Fallout Mob Mod@1.0, chunk_filter@0.13, Character Customization@0.13, Flan's Mod@0.13, Stacks@1.0, Small Utility Mod@1.0.0, Item Shop Mod@1.0.0, quest_markers@0.13, XlvsEnch@1.0.0, Radiation mod@0.13, CustomNpcs@1.7.10d, mcf_clanbases@0.13, mcf_lootcontainers@0.13, In-game NBTEdit@1.7.2.2, Oceancraft@1.4.1, spark@1.6.4`
- Java Version: `Temurin 1.8.0_402-b06`
- OS: `Debian12`

**Comment by EverNife** [comment]
Try adding `-noverify` to the java startup args

**Comment by ErriourMe** [comment]
> Try adding `-noverify` to the java startup args

Yes, it helps. Thank you!
