### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by KubiRem** [CrucibleMC/Crucible#2]
Gt New Horziosn modpack crashed with error running server launcher
[fml-server-latest.log](https://github.com/CrucibleMC/Crucible/files/3983310/fml-server-latest.log)
[latest.log](https://github.com/CrucibleMC/Crucible/files/3983311/latest.log)
[fml-junk-earlystartup.log](https://github.com/CrucibleMC/Crucible/files/3983312/fml-junk-earlystartup.log)

**Comment by brunoxkk0** [comment]
add jvm argument: `-noverify`

**Comment by KubiRem** [comment]
Time: 12/19/19 1:30 PM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: it/unimi/dsi/fastutil/longs/Long2ObjectOpenHashMap
	at io.github.crucible.wrapper.CrucibleChunkBlockHashMap.<init>(CrucibleChunkBlockHashMap.java:15)
	at net.minecraft.world.gen.ChunkProviderServer.<init>(ChunkProviderServer.java:108)
	at net.minecraft.world.WorldServer.func_72970_h(WorldServer.java:911)
	at net.minecraft.world.World.<init>(World.java:453)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:162)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:374)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:338)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:642)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 9 more
Caused by: java.lang.ArrayIndexOutOfBoundsException

**Comment by KubiRem** [comment]
[13:30:56] [Server thread/INFO]: Adding biome mapping 196 Snowy Forest at BiomeBase[196]
[13:30:56] [Server thread/INFO]: Adding biome mapping 199 Toxic Everglades at BiomeBase[199]
[13:30:56] [Server thread/INFO]: Adding biome mapping 200 rwg_riverIce at BiomeBase[200]
[13:30:56] [Server thread/INFO]: Adding biome mapping 202 rwg_riverCold at BiomeBase[202]
[13:30:56] [Server thread/INFO]: Adding biome mapping 205 rwg_riverTemperate at BiomeBase[205]
[13:30:56] [Server thread/INFO]: Adding biome mapping 207 rwg_riverHot at BiomeBase[207]
[13:30:56] [Server thread/INFO]: Adding biome mapping 209 rwg_riverWet at BiomeBase[209]
[13:30:56] [Server thread/INFO]: Adding biome mapping 211 rwg_riverOasis at BiomeBase[211]
[13:30:56] [Server thread/INFO]: Adding biome mapping 213 rwg_oceanIce at BiomeBase[213]
[13:30:56] [Server thread/INFO]: Adding biome mapping 214 rwg_oceanCold at BiomeBase[214]
[13:30:56] [Server thread/INFO]: Adding biome mapping 216 rwg_oceanTemperate at BiomeBase[216]
[13:30:56] [Server thread/INFO]: Adding biome mapping 218 rwg_oceanHot at BiomeBase[218]
[13:30:56] [Server thread/INFO]: Adding biome mapping 223 rwg_oceanOasis at BiomeBase[223]
[13:30:56] [Server thread/INFO]: Adding biome mapping 224 rwg_snowDesert at BiomeBase[224]
[13:30:56] [Server thread/INFO]: Adding biome mapping 225 rwg_snowForest at BiomeBase[225]
[13:30:56] [Server thread/INFO]: Adding biome mapping 226 rwg_coldPlains at BiomeBase[226]
[13:30:56] [Server thread/INFO]: Adding biome mapping 227 rwg_coldForest at BiomeBase[227]
[13:30:56] [Server thread/INFO]: Adding biome mapping 228 rwg_hotPlains at BiomeBase[228]
[13:30:56] [Server thread/INFO]: Adding biome mapping 229 rwg_hotForest at BiomeBase[229]
[13:30:56] [Server thread/INFO]: Adding biome mapping 230 rwg_hotDesert at BiomeBase[230]
[13:30:56] [Server thread/INFO]: Adding biome mapping 231 rwg_plains at BiomeBase[231]
[13:30:56] [Server thread/INFO]: Adding biome mapping 232 rwg_tropical at BiomeBase[232]
[13:30:56] [Server thread/INFO]: Adding biome mapping 233 rwg_redwood at BiomeBase[233]
[13:30:56] [Server thread/INFO]: Adding biome mapping 234 rwg_jungle at BiomeBase[234]
[13:30:56] [Server thread/INFO]: Adding biome mapping 235 rwg_oasis at BiomeBase[235]
[13:30:56] [Server thread/INFO]: Adding biome mapping 236 rwg_temperateForest at BiomeBase[236]
[13:30:56] [Server thread/INFO]: Adding biome mapping 237 rwg_oceanWet at BiomeBase[237]
[13:30:56] [Server thread/INFO]: Adding biome mapping 239 Australian Desert at BiomeBase[239]
[13:30:56] [Server thread/INFO]: Adding biome mapping 240 Australian Desert II at BiomeBase[240]
[13:30:56] [Server thread/INFO]: Adding biome mapping 241 Australian Desert III at BiomeBase[241]
[13:30:56] [Server thread/INFO]: Adding biome mapping 242 Plainlands at BiomeBase[242]
[13:30:56] [Server thread/INFO]: Adding biome mapping 243 Australian Outback at BiomeBase[243]
[13:30:56] [Server thread/INFO]: Adding biome mapping 244 Australian Ocean at BiomeBase[244]
[13:30:56] [Server thread/INFO]: Adding biome mapping 245 Australian Forest at BiomeBase[245]
[13:30:56] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: it/unimi/dsi/fastutil/longs/Long2ObjectOpenHashMap
	at io.github.crucible.wrapper.CrucibleChunkBlockHashMap.<init>(CrucibleChunkBlockHashMap.java:15) ~[CrucibleChunkBlockHashMap.class:1.7.10-1614.1.0.7]
	at net.minecraft.world.gen.ChunkProviderServer.<init>(ChunkProviderServer.java:108) ~[ms.class:?]
	at net.minecraft.world.WorldServer.func_72970_h(WorldServer.java:911) ~[mt.class:?]
	at net.minecraft.world.World.<init>(World.java:453) ~[ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:162) ~[mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:374) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:338) ~[lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:642) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.lang.ClassNotFoundException: it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_232]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_232]
	... 9 more
Caused by: java.lang.ArrayIndexOutOfBoundsException
[13:30:56] [Server thread/ERROR]: 	Cause of unexpected exception was
java.lang.ClassNotFoundException: it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_232]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_232]
	at io.github.crucible.wrapper.CrucibleChunkBlockHashMap.<init>(CrucibleChunkBlockHashMap.java:15) ~[CrucibleChunkBlockHashMap.class:1.7.10-1614.1.0.7]
	at net.minecraft.world.gen.ChunkProviderServer.<init>(ChunkProviderServer.java:108) ~[ms.class:?]
	at net.minecraft.world.WorldServer.func_72970_h(WorldServer.java:911) ~[mt.class:?]
	at net.minecraft.world.World.<init>(World.java:453) ~[ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:162) ~[mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:374) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:338) ~[lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:642) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.lang.ArrayIndexOutOfBoundsException
[13:30:56] [Server thread/ERROR]: This crash report has been saved to: /usr/games/mc/CrucibleServerWorking/./crash-reports/crash-2019-12-19_13.30.56-server.txt
[13:30:57] [Server thread/INFO]: Applying holder lookups
[13:30:57] [Server thread/INFO]: Holder lookups applied
[13:30:57] [pool-7-thread-1/INFO]: ServerChannelRegister: Dimensional Transceiver data saved to /usr/games/mc/CrucibleServerWorking/./World/enderio/dimensionalTransceiver.json
[13:30:57] [Server thread/WARN]: Error handling file saving: Did the server never start?
[13:30:57] [Server thread/INFO]: The state engine was in incorrect state SERVER_STARTING and forced into state SERVER_STOPPED. Errors may have been discarded.

**Comment by brunoxkk0** [comment]
Update your libraries, to the latest ones.

**Comment by KubiRem** [comment]
still

**Comment by KubiRem** [comment]
using CentOS

**Comment by juanmuscaria** [comment]
Please download the libraries again, apparently some libraries were missing.
https://github.com/CrucibleMC/Crucible/releases/download/v2.0/libraries.zip

**Comment by KubiRem** [comment]
I have never seen more stable 1.7.10 server.
There are no bugs no lags at the moment.
I will test more and share it wit You.
Thank You so much!!!

**Comment by evernife** [comment]
We use this build in our own public servers, but, as always, backup your server before any update :D

Checkout https://github.com/CrucibleMC/Grimoire-Mixins as well, i will publish a realease very soon.
