### ISSUE TITLE
IndustrialCraft 2 exp error with cables break

### ISSUE THREAD

**Issue by perezzloy** [CrucibleMC/Crucible#21]
Crucible build: 1.7.10-3.1
IC2exp version: 2-2.2.827

An error occurs when trying to break any cable from this mod. In addition, the cables don't connect.

```
[18:23:42 WARN]: Failed to handle packet for /127.0.0.1:7065
java.lang.NullPointerException
        at ic2.core.block.wiring.BlockCable.removedByPlayer(BlockCable.java:376) ~[BlockCable.class:?]
        at net.minecraft.block.Block.removedByPlayer(Block.java:1375) ~[aji.class:?]
        at net.minecraft.server.management.ItemInWorldManager.removeBlock(ItemInWorldManager.java:309) ~[mx.class:?]
        at net.minecraft.server.management.ItemInWorldManager.func_73079_d(ItemInWorldManager.java:302) ~[mx.class:?]
        at net.minecraft.server.management.ItemInWorldManager.func_73084_b(ItemInWorldManager.java:346) ~[mx.class:?]
        at net.minecraft.server.management.ItemInWorldManager.func_73074_a(ItemInWorldManager.java:183) ~[mx.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:743) ~[nh.class:?]
        at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8) ~[ji.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) ~[ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1033) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:852) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:702) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
[18:23:42 INFO]: player324 lost connection: Internal server error
```

**Comment by juanmuscaria** [comment]
https://github.com/CrucibleMC/Crucible#know-incompatibilities-and-bugs

**Comment by perezzloy** [comment]
Thanks! It works! Sorry, I didn’t notice in the description ...
