### ISSUE TITLE
Crash server

### ISSUE THREAD

**Issue by xli2td** [CrucibleMC/Crucible#50]
Version: 4.1
Java: 8x64

[fml-junk-earlystartup.log](https://github.com/CrucibleMC/Crucible/files/5857578/fml-junk-earlystartup.log)
[fml-server-latest.log](https://github.com/CrucibleMC/Crucible/files/5857579/fml-server-latest.log)
[latest.log](https://github.com/CrucibleMC/Crucible/files/5857580/latest.log)

0:40:03] [main/ERROR] [LaunchWrapper/]: Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281]
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:46) [Crucible-1.7.10-4.1-server.jar:1.7.10-4.1]
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:15) [Crucible-1.7.10-4.1-server.jar:1.7.10-4.1]

**Comment by juanmuscaria** [comment]
You need to add -noverify to your jvm arguments https://github.com/CrucibleMC/Crucible#know-incompatibilities-and-bugs

**Comment by juanmuscaria** [comment]
I'll be closing this issue for now, it the issue persist reopen this issue.
