### ISSUE TITLE
TAB plugin compatibility

### ISSUE THREAD

**Issue by UknownGino** [CrucibleMC/Crucible#54]
**Server version**
CrucibleMC 5.0

**TAB plugin version**
2.8.10

**TAB Download link**
https://www.spigotmc.org/resources/tab-1-7-x-1-16-5.57806/

**Bug description**
The plugin throws a class not found exception at startup and disables itself when used with cruciblemc.

**How to reproduce**
Install CrucibleMC, the TAB plugin and try to start the server.

**The error itself**
```
[13:59:16 INFO]: [TAB] Enabling TAB v2.8.10
[13:59:16 INFO]: [TAB] Server version: 1.7.10 (v1_7_R4)
[13:59:16 INFO]: [TAB] Your server version is marked as compatible, but a compatibility issue was found. Please report the error below (include your server version & fork too)
[13:59:16 WARN]: java.lang.ClassNotFoundException: net/minecraft/server/v1_7_R4/IChatBaseComponent
[13:59:16 WARN]:        at java.lang.Class.forName0(Native Method)
[13:59:16 WARN]:        at java.lang.Class.forName(Class.java:264)
[13:59:16 WARN]:        at me.neznamy.tab.platforms.bukkit.nms.PacketPlayOut.getNMSClass(PacketPlayOut.java:47)
[13:59:16 WARN]:        at me.neznamy.tab.platforms.bukkit.nms.NMSHook.isVersionSupported(NMSHook.java:114)
[13:59:16 WARN]:        at me.neznamy.tab.platforms.bukkit.Main.onEnable(Main.java:21)
[13:59:16 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[13:59:16 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:362)
[13:59:16 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:409)
[13:59:16 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:399)
[13:59:16 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:333)
[13:59:16 WARN]:        at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:513)
[13:59:16 WARN]:        at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:487)
[13:59:16 WARN]:        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:447)
[13:59:16 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336)
[13:59:16 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:641)
[13:59:16 WARN]:        at java.lang.Thread.run(Thread.java:748)
[13:59:16 INFO]: [TAB] Disabling TAB v2.8.10
```
![error](https://user-images.githubusercontent.com/61624086/108364522-72fcdd80-71f6-11eb-9afc-65268c3d5b1e.png)

**Issue reported also on the TAB plugin github**
https://github.com/NEZNAMY/TAB/issues/277

**Comment by evernife** [comment]
Just to point here a comment from our discord:

```
Jolly Roger:

I've seen the latest github issue. Even if you convert all of the TAB NMS classes to Crucible ones and replace Class.forName with Plugin.class.getLoader().loadClass() TAB still doesn't work
You'd just have to make a custom plugin for crucible, or get to know TAB pretty well and adapt it
Problem is TAB doesn't have many 1.7.10 features anyway so it's better to just rewrite the plugin with the features you want
```

Tab plugins are incompatible with Thermos from a long time T.T, i think for 1.7.10 the best solution is create a custom mod for the tab.

**Comment by tacopeland** [comment]
(I'm Jolly Roger in Discord)
If you want to see what I've tried to get the TAB plugin compatible with Crucible check this out: https://github.com/tacopeland/TAB/commit/a494a75081f6af310d0bf11c7d84d2ef9a323bf4
If you want to try this version of TAB out yourself you'll have to clone this and run a `mvn deploy` on it.

Basically even with TAB running relatively error-free, it has barely any features on 1.7.10 (it pretty much only messes with people's names in the tab list, puts custom numbers where the ping would be and has a scoreboard you can use on the right side of your screen) and isn't really worth using. People usually just use Bungee if they want to segregate people in their tab list and say "welcome" or something.

If you really want to make this work as a plugin you may have to generate yourself a javadoc for ProtocolLib 3.7.0 and see if it lets you send custom tablist packets in 1.7.10.

**Comment by NEZNAMY** [comment]
I would like to ask about https://github.com/NEZNAMY/TAB/compare/master...tacopeland:master#diff-e0cba3a1dcc21b91fb2f9d9fa7eeb4e64ed8724c5d24840f27f2c051eb9298e7L47-R48. I tried it, however I am getting a NPE (http://prntscr.com/102quba). Am I missing something?

**Comment by tacopeland** [comment]
What's happening there is that `Main.class.getClassLoader().loadClass()` seems to give you a `NullPointerException` rather than a `ClassNotFoundException` like `Class.forName()` if it can't find the class, so your try-catch isn't catching it.

**Comment by tacopeland** [comment]
After this, you will get a heap of errors like `java.lang.NoSuchFieldException: a`, which is caused by `Class.getDeclaredField()` using SRG fields rather than Bukkit ones. Then after you manually remap all of those to SRG fields you'll have to do the same for the methods. Doing so will make the resulting jar only useful for Crucible probably.
This is because Crucible doesn't remap fields in `Class.getDeclaredField()`.
If you managed to load the method through the plugin's class loader then Crucible may be able to remap these fields and methods.

**Comment by NEZNAMY** [comment]
That NPE throw explains it, for fields I have a solution that will work on both. Will let you know if I get it to work.

**Comment by NEZNAMY** [comment]
I was able to get this to work, thanks for the help.

**Comment by evernife** [comment]
Fixed at https://github.com/NEZNAMY/TAB/issues/277, download link https://github.com/NEZNAMY/TAB/releases/tag/2.8.11-pre5
