### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by creci** [CrucibleMC/Crucible#58]
Crash when using my server wrapper on Crucible v5.0. There is no such thing on the old version.

Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at cpw.mods.fml.common.versioning.ComparableVersion.parseVersion(ComparableVersion.java:383)
	at cpw.mods.fml.common.versioning.ComparableVersion.<init>(ComparableVersion.java:374)
	at cpw.mods.fml.common.versioning.DefaultArtifactVersion.<init>(DefaultArtifactVersion.java:25)
	at cpw.mods.fml.common.versioning.DefaultArtifactVersion.<init>(DefaultArtifactVersion.java:36)
	at cpw.mods.fml.common.DummyModContainer.getProcessedVersion(DummyModContainer.java:135)
	at cpw.mods.fml.common.InjectedModContainer.getProcessedVersion(InjectedModContainer.java:124)
	at cpw.mods.fml.common.Loader.sortModList(Loader.java:222)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:495)
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:319)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:175)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:641)
	at java.lang.Thread.run(Thread.java:748)

**Comment by evernife** [comment]
Can you send us the entire log?

Else, what do you mean by "my server wrapper", what is "your server wrapper" ?

**Comment by creci** [comment]
The problem was that the version was not displayed, I rebuilt the kernel by specifying the kernel version manually, which solved my problem.

**Comment by evernife** [comment]
I didn't understand anything haha, but I'm happy that everything worked out.
