### ISSUE TITLE
Crash with RecurrentComplex

### ISSUE THREAD

**Issue by Noire86** [CrucibleMC/Crucible#62]
It crashes upon startup. Something with 
Caused by: java.lang.NoSuchMethodError: joptsimple.internal.Strings.join(Ljava/util/List;Ljava/lang/String;)Ljava/lang/String;
	at ivorius.reccomplex.structures.generic.matchers.BiomeMatcher.ofTypes(BiomeMatcher.java:47)
	at ivorius.reccomplex.RCRegistryHandler.registerBiomePresets(RCRegistryHandler.java:276)
	at ivorius.reccomplex.RCRegistryHandler.preInit(RCRegistryHandler.java:156)
	at ivorius.reccomplex.RecurrentComplex.preInit(RecurrentComplex.java:121)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

Full log provided below

[crash-2021-03-12_09.13.59-server.txt](https://github.com/CrucibleMC/Crucible/files/6128879/crash-2021-03-12_09.13.59-server.txt)

**Comment by Noire86** [comment]
Sorry, I`m too blind to see this as a duplicate of #41 

Closed.

**Comment by juanmuscaria** [comment]
It's fixed in the latest dev builds https://juanmuscaria.beta.teamcity.com/buildConfiguration/Crucible_Dev
