### ISSUE TITLE
ServerWrapper crash on Startup

### ISSUE THREAD

**Issue by evernife** [CrucibleMC/Crucible#63]
When starting CrucibleMC with a Sever Wrapper, the server will not start chashing when comparaing versions of the mods.

```
java.lang.NullPointerException: Exception in server tick loop
	at cpw.mods.fml.common.versioning.ComparableVersion.parseVersion(ComparableVersion.java:383)
	at cpw.mods.fml.common.versioning.ComparableVersion.<init>(ComparableVersion.java:374)
	at cpw.mods.fml.common.versioning.DefaultArtifactVersion.<init>(DefaultArtifactVersion.java:25)
	at cpw.mods.fml.common.versioning.DefaultArtifactVersion.<init>(DefaultArtifactVersion.java:36)
	at cpw.mods.fml.common.DummyModContainer.getProcessedVersion(DummyModContainer.java:135)
	at cpw.mods.fml.common.InjectedModContainer.getProcessedVersion(InjectedModContainer.java:124)
	at cpw.mods.fml.common.Loader.sortModList(Loader.java:222)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:495)
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:87)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:319)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:175)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:642)
	at java.lang.Thread.run(Thread.java:748)
```

Error is caused by a uncomplete reading of the MAINFEST's array.

**Comment by Noire86** [comment]
Add Crucible META-INF contents to the ServerWrapper META-INF file. It will help

**Comment by juanmuscaria** [comment]
Can anyone test the latest dev build with the fix? Remember to use a server wrapper without the meta inf modification.

**Comment by xmssss** [comment]
For me, latest dev build is working fine, without this NPE
