### ISSUE TITLE
MiaoMenu Plug-in is not available , jdk/nashorn/api/scripting/URLReader

### ISSUE THREAD

**Issue by xiamo070091** [CrucibleMC/Crucible#70]
When using the plug-in MiaoMenu does not support, and the error is as follows. Is this a server-side problem? It can run very well in the Uranium server.

[Plugin-MiaoMenu.zip](https://github.com/CrucibleMC/Crucible/files/6621708/Plugin-MiaoMenu.zip)

This error is also reported when loading without plugman.

```
org.bukkit.command.CommandException: Unhandled exception executing command 'plugman' in plugin PlugMan v2.1.7
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:1.7.10-5.0-master-f045cf2]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:188) ~[SimpleCommandMap.class:1.7.10-5.0-master-f045cf2]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:699) ~[CraftServer.class:1.7.10-5.0-master-f045cf2]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchServerCommand(CraftServer.java:680) [CraftServer.class:1.7.10-5.0-master-f045cf2]
	at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:473) [lt.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:842) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:692) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.NoClassDefFoundError: jdk/nashorn/api/scripting/URLReader
	at pw.yumc.MiaoMenu.MiaoMenu.onLoad(MiaoMenu.java:45) ~[?:?]
	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:365) ~[?:?]
	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:318) ~[?:?]
	at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:380) ~[?:?]
	at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122) ~[?:?]
	at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:1.7.10-5.0-master-f045cf2]
	... 8 more
```

**Comment by evernife** [comment]
First, can you try to load the plugin without Plugman?

----------------

I did some serach at this issue here https://github.com/GoogleCloudPlatform/app-gradle-plugin/issues/160 that seems to be similar to the problem this plugin is having to be loaded up.

This repo show us some tips as well https://github.com/mpoehler/hbs-test

**Comment by xiamo070091** [comment]
In the absence of plugman, the plug-in is also unavailable.

**Comment by evernife** [comment]
Where can i download this plugin for me to test it?
I was not able to find it on Spigot.

Can you give me a link or is it a paid plugin?

**Comment by xiamo070091** [comment]
[Plugin-MiaoMenu.zip](https://github.com/CrucibleMC/Crucible/files/6621799/Plugin-MiaoMenu.zip)
I uploaded the file.

**Comment by juanmuscaria** [comment]
Looks like you have a plugin that uses jdk specific classes running on jre

**Comment by xiamo070091** [comment]
It is solved. It does not require a specific jdk, but it requires the server core to load some things.
The author of this plugin and the author of the server core I used before have modified the server api and added the nashorn engine. Just add a line of code to FMLLaunchHandler.

```
    private FMLLaunchHandler(LaunchClassLoader launchLoader, FMLTweaker tweaker)
    {
 +       this.classLoader.addClassLoaderExclusion("jdk.nashorn.");
    }
```
