### ISSUE TITLE
RawMessages S02PacketChat

### ISSUE THREAD

**Issue by microwin7** [CrucibleMC/Crucible#77]
```
[09:09:08 INFO]: [CMI] Error {0}
[09:09:08 INFO]: [CMI] java.lang.ClassNotFoundException: net/minecraft/server/v1_7_R4/PacketPlayOutChat
[09:09:08 WARN]: java.lang.NullPointerException
[09:09:08 WARN]:        at com.Zrips.CMI.Modules.RawMessages.RawMessageManager.send(RawMessageManager.java:110)
[09:09:08 WARN]:        at com.Zrips.CMI.Modules.RawMessages.RawMessage.show(RawMessage.java:605)
[09:09:08 WARN]:        at com.Zrips.CMI.Modules.RawMessages.RawMessage.show(RawMessage.java:637)
[09:09:08 WARN]:        at com.Zrips.CMI.Modules.RawMessages.RawMessage.show(RawMessage.java:631)
[09:09:08 WARN]:        at com.Zrips.CMI.utils.VersionChecker.lambda$0(VersionChecker.java:101)
[09:09:08 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:76)
[09:09:08 WARN]:        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[09:09:08 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[09:09:08 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[09:09:08 WARN]:        at java.lang.Thread.run(Thread.java:748)
[09:09:53 INFO]: Error {0}
[09:09:53 INFO]: java.lang.ClassNotFoundException: net/minecraft/server/v1_7_R4/PacketPlayOutChat
```

RU
Пробовал на всех возможных модовых ядрах, результат всё время такой
Thermos и другие выдают данную ошибку, мои попытки как-то переписать ядро самостоятельно обвенчались неудачей
Я лишь могу сказать что на чистом Spigot 1.7.10 эти сообщения отправляются правильно

Возможно вы мне сможете помочь с этой проблемой, очень надеюсь на это

EN Translate
Tried it on all possible mod cores, the result is like this all the time
Thermos and others give this error, my attempts to somehow rewrite the kernel on my own were unsuccessful
I can only say that on pure Spigot 1.7.10 these messages are sent correctly

Perhaps you can help me with this problem, I really hope so

**Comment by microwin7** [comment]
Вот ещё, при уже вызове командой
Here's another, when already called by the command
```
java.lang.NullPointerException
at com.Zrips.CMI.Modules.RawMessages.RawMessageManager.send(RawMessageManager.java:110)
at com.Zrips.CMI.Modules.RawMessages.RawMessage.show(RawMessage.java:605)
at com.Zrips.CMI.Modules.RawMessages.RawMessage.show(RawMessage.java:588)
at com.Zrips.CMI.CMI.ShowPagination(CMI.java:2361)
at com.Zrips.CMI.CMI.ShowPagination(CMI.java:2333)
at com.Zrips.CMI.CMI.ShowPagination(CMI.java:2316)
at com.Zrips.CMI.CMI.ShowPagination(CMI.java:2308)
at com.Zrips.CMI.commands.CommandsHandler.help(CommandsHandler.java:527)
at com.Zrips.CMI.commands.CommandsHandler.onCommand(CommandsHandler.java:175)
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:188)
at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:702)
at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1381)
at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1118)
at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38)
at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53)
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245)
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:990)
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:808)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:683)
at java.lang.Thread.run(Thread.java:748)
```

**Comment by juanmuscaria** [comment]
There's not much we can do unless the plugin author uses MCP names for reflection. Cauldron reflection remaping has a lot of problems and it's on our todo list to change how the plugin classloader works. Being a closed source plugin doesn't help either since you can't patch the plugin.

**Comment by xstmass** [comment]
CMI plugin is partial working on UraniumMC, include clickable messages. But some errors still exist.

**Comment by evernife** [comment]
UraniumMC is a chinese fork, we are brazilians, you are russian, too hard for us to even understand what they do T.T

English commits would have helped us.

**Comment by Irgendwer01** [comment]
> UraniumMC is a chinese fork, we are brazilians, you are russian, too hard for us to even understand what they do T.T
> 
> English commits would have helped us.

@evernife It's buggy, abandoned (last update was august) and their latest releases not even work really.

**Comment by 8MiYile** [comment]
It's important to know when this will be resolved

**Comment by EverNife** [comment]
Probably one of the most hard things to be done. T.T

**Comment by EverNife** [comment]
Any PR able to contribute to this matter is welcome
