### ISSUE TITLE
Change "disable Forge's version check" setting to true by default

### ISSUE THREAD

**Issue by microwin7** [CrucibleMC/Crucible#78]
[02:55:40 INFO]: Default game type: SURVIVAL
[02:55:41 WARN]: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1
[02:55:41 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:815)
[02:55:41 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:768)
[02:55:41 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:717)
[02:55:41 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:689)
[02:55:41 WARN]:        at net.minecraftforge.common.ForgeVersion$1.run(ForgeVersion.java:95)
[02:55:41 WARN]: Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1
[02:55:41 WARN]:        at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:374)
[02:55:41 WARN]:        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:183)
[02:55:41 WARN]:        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
[02:55:41 WARN]:        at com.google.gson.Gson.fromJson(Gson.java:803)
[02:55:41 WARN]:        ... 4 more

**Comment by juanmuscaria** [comment]
You can ignore it, it's forge's version checker breaking because forge changed how their stuff works.

**Comment by Aizistral** [comment]
Maybe this could be fixed in Crucible? Not that we need version checker at all now that Forge doesn't update for 1.7.10 whatsoever.

**Comment by Pilad** [comment]
> 
> 
> Maybe this could be fixed in Crucible? Not that we need version checker at all now that Forge doesn't update for 1.7.10 whatsoever.

Open forge.cfg and disable:
    # Set to true to disable Forge's version check mechanics. Forge queries a small json file on our server for version information. For more details see the ForgeVersion class in our github.
    B:disableVersionCheck=false

**Comment by Aizistral** [comment]
I know that config exists. And I absolutely don't see how its existance is related to my suggestion.

**Comment by spannerman79** [comment]
In https://github.com/CrucibleMC/Crucible/blob/master/forge/src/main/java/net/minecraftforge/common/ForgeModContainer.java#L70 change to `    public static boolean disableVersionCheck = true;`

In https://github.com/CrucibleMC/Crucible/blob/master/forge/src/main/java/net/minecraftforge/common/ForgeModContainer.java#L135 change to `        prop = config.get(CATEGORY_GENERAL, "disableVersionCheck", true);`

Or rip out the version check fully starting from https://github.com/CrucibleMC/Crucible/blob/master/forge/src/main/java/net/minecraftforge/common/ForgeVersion.java#L79

**Comment by juanmuscaria** [comment]
The check was removed on 8b580e32f15c42c9f204e098808457313f59f936
